{% set name = "requests_pkcs12" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b49d0317c680572d8cce9c16af140134e40ad1871ffbc5afa3b2470ad439eeba

build:
  noarch: python
  number: 1000
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - pyopenssl >=0.14
    - requests >=2.18.4

test:
  imports:
    - requests_pkcs12

about:
  home: https://github.com/m-click/requests_pkcs12
  license: ISC
  license_family: BSD
  license_file: LICENSE
  summary: 'This library adds PKCS#12 support to the Python requests library.'

  description: |
    Add PKCS#12 support to the requests library in a clean way, without monkey
    patching or temporary files
  dev_url: https://github.com/m-click/requests_pkcs12

extra:
  recipe-maintainers:
    - sodre
