travis:
  secure:
    BINSTAR_TOKEN: 0lJTGqtSxpHtmshHy1mjmS+BCYCC3W+KCuzZEpTmvYtSpLcMlNDO7MqcLylYrvtDSbtflZY7Yh4LsNcJUal6nsQINGEv0COf8Sg2xDHaUHuh+wL3qmG1VpRPyf0TMWkWNkXuKe61VgM21obYhi4XYahwXVV1aRIqLyTzdbey7WMyzUCN0EjaKiFEE0pzKbpOS5vPKH+vbhrJHazuS2x6XqxCoPqPPCbPejCY4dhxjVnK0VCZ7sg7xMgT95hA8Y/V+aJtQPzaZyTIfwjBIkRDJY6aeM6KuSO9DEc3JCfGnZiy4GM8ws/GtR44F1/bYgkHjXpuP8whhbFdoZpve37jSH3SdMMLpmRPtP0fl8ESXhi7xED0uvvKf4MYR7y8WGgqfh9X/yZJrvJKIs29X0yXfOtHt6zAkLuLa1rLoW5OZV/83iMGZ+JuL9M4OP3VgaXHZqibD/qXObPN1GEb6IfYkd7jC0AiR+6kyomEt9p4C6Tpq+OJEWMgdQIJsRC6BvoV/98Y5/20iY5jakybqhEwRBW+LU9CWl46TD6wjyA+x2yEfqXZqWWnrfg9U790piQORwnywK/Xw3SIy/lnPCN5mcwi5kdryiuviD0iH17xjn6FoQEjeU/LYo38GMgLby8riw5VpteYEDqrajKAhF5iDTKUOEdncx1AiGY0Nk2kvw0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
